#!/usr/bin/env python3
"""
Attack: RSA with primes generated by LCG chunk-wise (e.g. Google CTF Chunk Norris)
Each 64-bit chunk of prime p is generated via s_{i+1} = a * s_i mod 2^chunk_size.
"""

import gmpy2
import sympy
from Crypto.Util.number import long_to_bytes
import os
import re

def solve(n=None, e=None, c=None, filepath=None, **kwargs):
    if not n or not e or not c:
        return None

    # Check for multiplier 'a' in folder if challenge.py exists
    a = 0xe64a5f84e2762be5
    chunk_size = 64

    if filepath:
        folder = os.path.dirname(filepath)
        for cand in ["challenge.py", "chall.py"]:
            cpath = os.path.join(folder, cand)
            if os.path.exists(cpath):
                try:
                    txt = open(cpath, "r", encoding="utf-8", errors="ignore").read()
                    m_a = re.search(r"a\s*=\s*(0x[0-9a-fA-F]+|\d+)", txt)
                    if m_a:
                        a = int(m_a.group(1), 0)
                    m_cs = re.search(r"chunk_size\s*=\s*(\d+)", txt)
                    if m_cs:
                        chunk_size = int(m_cs.group(1), 0)
                except Exception:
                    pass

    try:
        a_inv = gmpy2.invert(a, 2**chunk_size)
        ab = n % (2**chunk_size)
        abg = (a_inv * ab * 2) % (2**chunk_size)
        xab = (n - (abg << chunk_size)) % (2**(chunk_size * 2))

        for x in sympy.divisors(int(xab)):
            if x.bit_length() <= chunk_size and xab // x <= x:
                chunks = n.bit_length() // (chunk_size * 2)
                p = 0
                cur_a = x
                for i in range(chunks):
                    p += cur_a << (i * chunk_size)
                    cur_a = (cur_a * a_inv) % (2**chunk_size)
                if p > 1 and n % p == 0:
                    q = n // p
                    phi = (p - 1) * (q - 1)
                    if gmpy2.gcd(e, phi) == 1:
                        d = gmpy2.invert(e, phi)
                        pt = pow(c, d, n)
                        m_bytes = long_to_bytes(int(pt))
                        match = re.search(rb"[A-Za-z0-9_]+\{[ -~]+\}", m_bytes)
                        if match:
                            return match.group(0).decode("utf-8", errors="ignore")
                        if b"CTF{" in m_bytes or b"flag{" in m_bytes:
                            return m_bytes.decode("utf-8", errors="ignore").strip()
    except Exception:
        pass

    return None

if __name__ == "__main__":
    n = 0xab802dca026b18251449baece42ba2162bf1f8f5dda60da5f8baef3e5dd49d155c1701a21c2bd5dfee142fd3a240f429878c8d4402f5c4c7f4bc630c74a4d263db3674669a18c9a7f5018c2f32cb4732acf448c95de86fcd6f312287cebff378125f12458932722ca2f1a891f319ec672da65ea03d0e74e7b601a04435598e2994423362ec605ef5968456970cb367f6b6e55f9d713d82f89aca0b633e7643ddb0ec263dc29f0946cfc28ccbf8e65c2da1b67b18a3fbc8cee3305a25841dfa31990f9aab219c85a2149e51dff2ab7e0989a50d988ca9ccdce34892eb27686fa985f96061620e6902e42bdd00d2768b14a9eb39b3feee51e80273d3d4255f6b19
    e = 0x10001
    c = 0x6a12d56e26e460f456102c83c68b5cf355b2e57d5b176b32658d07619ce8e542d927bbea12fb8f90d7a1922fe68077af0f3794bfd26e7d560031c7c9238198685ad9ef1ac1966da39936b33c7bb00bdb13bec27b23f87028e99fdea0fbee4df721fd487d491e9d3087e986a79106f9d6f5431522270200c5d545d19df446dee6baa3051be6332ad7e4e6f44260b1594ec8a588c0450bcc8f23abb0121bcabf7551fd0ec11cd61c55ea89ae5d9bcc91f46b39d84f808562a42bb87a8854373b234e71fe6688021672c271c22aad0887304f7dd2b5f77136271a571591c48f438e6f1c08ed65d0088da562e0d8ae2dadd1234e72a40141429f5746d2d41452d916
    print("Standalone test:", solve(n=n, e=e, c=c))
